### ISSUE TITLE
Preprocessing XML error

### ISSUE THREAD

**Issue by bxh9261** [EastonWang/StageDP#8]
At the end of preprocessing the data and attempting to create the .fmerge file I'm given this error

`Merge parsed files to generate *.merge file...
Processing file: .../StageDP/rst_discourse_treebank/data/RSTtrees-WSJ-main-1.0/TEST/wsj_0602.out.text.xml
Traceback (most recent call last):
  File "preprocess.py", line 98, in <module>
    main()
  File "preprocess.py", line 93, in main
    extract(fxml)
  File "preprocess.py", line 19, in extract
    sent_list, const_list = reader(fxml)
  File "/home/blaise/Desktop/Wang-2017-RST/StageDP/src/utils/xmlreader.py", line 123, in reader
    xmldoc = minidom.parse(fname)
  File "/home/blaise/miniconda3/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/home/blaise/miniconda3/lib/python3.8/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/home/blaise/miniconda3/lib/python3.8/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
`

It appears there is an error in the creation of the xml files, could someone advise?

**Comment by bxh9261** [comment]
my solution was to change line 20 of run_corenlp.sh to

`/usr/bin/java -mx2g -cp "$scriptdir/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse -file $FNAME -outputDirectory $PATH -outputFormat xml -outputExtension '.xml'`
